"""empty message

Revision ID: 080ed13eba0f
Revises: 4a47cecaa1be
Create Date: 2023-11-28 08:46:17.814133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080ed13eba0f'
down_revision: Union[str, None] = '4a47cecaa1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ID_TOKEN', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ID_TOKEN')
    # ### end Alembic commands ###
