"""empty message

Revision ID: 188b2cc7e1ec
Revises: 82372dde6fea
Create Date: 2023-11-20 14:44:54.155425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '188b2cc7e1ec'
down_revision: Union[str, None] = '82372dde6fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_goal', sa.Column('START_DT', sa.Date(), nullable=True))
    op.add_column('team_goal', sa.Column('END_DT', sa.Date(), nullable=True))
    op.alter_column('team_goal', 'TEAM_GOAL_NM',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_goal', 'TEAM_GOAL_NM',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('team_goal', 'END_DT')
    op.drop_column('team_goal', 'START_DT')
    # ### end Alembic commands ###
