"""empty message

Revision ID: 321db0877413
Revises: 8890f2f14522
Create Date: 2023-11-20 09:16:02.510661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321db0877413'
down_revision: Union[str, None] = '8890f2f14522'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_master', sa.Column('MODIFY_DT', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge_master', 'MODIFY_DT')
    # ### end Alembic commands ###
