"""empty message

Revision ID: 35a0369c7f11
Revises: 321db0877413
Create Date: 2023-11-20 09:54:08.603045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35a0369c7f11'
down_revision: Union[str, None] = '321db0877413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_master', sa.Column('USER_ID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'challenge_master', 'user', ['USER_ID'], ['USER_NO'])
    op.alter_column('challenge_user', 'STATUS',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED', name='AcceptType'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('challenge_user', 'STATUS',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'DECLINED', 'BLOCKED', name='AcceptType'),
               nullable=False)
    op.drop_constraint(None, 'challenge_master', type_='foreignkey')
    op.drop_column('challenge_master', 'USER_ID')
    # ### end Alembic commands ###
