"""empty message

Revision ID: 461d4bc581ee
Revises: 2f775b3b98a6
Create Date: 2023-12-01 00:17:30.952181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '461d4bc581ee'
down_revision: Union[str, None] = '2f775b3b98a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_user',
    sa.Column('ITEM_NO', sa.INTEGER(), server_default=sa.text('nextval(\'"item_user_ITEM_NO_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('COUNT', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CHALLENGE_USER_NO', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ITEM_USER_NO', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['CHALLENGE_USER_NO'], ['challenge_users.CHALLENGE_USER_NO'], name='item_user_CHALLENGE_USER_NO_fkey'),
    sa.ForeignKeyConstraint(['ITEM_NO'], ['item.ITEM_NO'], name='item_user_ITEM_NO_fkey'),
    sa.PrimaryKeyConstraint('ITEM_NO', name='item_user_pkey')
    )
    # ### end Alembic commands ###
