"""empty message

Revision ID: 62e3c9e8841b
Revises: b588c73c1f0a
Create Date: 2023-12-04 11:41:24.868441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62e3c9e8841b'
down_revision: Union[str, None] = 'b588c73c1f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_log', sa.Column('ITEM_NO', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item_log', 'item', ['ITEM_NO'], ['ITEM_NO'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_log', type_='foreignkey')
    op.drop_column('item_log', 'ITEM_NO')
    # ### end Alembic commands ###
