"""empty message

Revision ID: 7461f5d9a56f
Revises: b2b6b17949d9
Create Date: 2023-12-07 09:28:38.269942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7461f5d9a56f'
down_revision: Union[str, None] = 'b2b6b17949d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_complete_user',
    sa.Column('DAILY_COMPLETE_USER_NO', sa.Integer(), nullable=False),
    sa.Column('EMOJI', sa.String(), nullable=True),
    sa.Column('DAILY_COMPLETE_NO', sa.Integer(), nullable=True),
    sa.Column('CHALLENGE_USER_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_USER_NO'], ['challenge_users.CHALLENGE_USER_NO'], ),
    sa.ForeignKeyConstraint(['DAILY_COMPLETE_NO'], ['person_daily_goal_complete.DAILY_COMPLETE_NO'], ),
    sa.PrimaryKeyConstraint('DAILY_COMPLETE_USER_NO')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_complete_user')
    # ### end Alembic commands ###
