"""empty message

Revision ID: 75222199a503
Revises: 78df7907d6ab
Create Date: 2023-11-16 08:53:49.396827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75222199a503'
down_revision: Union[str, None] = '78df7907d6ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_goal', sa.Column('INSERT_DT', sa.DateTime(), nullable=True))
    op.add_column('team_goal', sa.Column('MODIFY_DATE', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_goal', 'MODIFY_DATE')
    op.drop_column('team_goal', 'INSERT_DT')
    # ### end Alembic commands ###
