"""empty message

Revision ID: 78df7907d6ab
Revises: 
Create Date: 2023-11-15 11:20:29.629723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78df7907d6ab'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('USER_NO', sa.Integer(), nullable=False),
    sa.Column('REGISTER_DT', sa.DateTime(), nullable=True),
    sa.Column('UPDATE_DT', sa.DateTime(), nullable=True),
    sa.Column('RECENT_LOGIN_DT', sa.DateTime(), nullable=True),
    sa.Column('DISABLE_YN', sa.Boolean(), nullable=True),
    sa.Column('DISABLE_DT', sa.DateTime(), nullable=True),
    sa.Column('SIGN_TYPE', sa.Enum('KAKAO', 'APPLE', 'GUEST', name='LoginType'), nullable=True),
    sa.Column('USER_NM', sa.String(), nullable=True),
    sa.Column('UID', sa.Integer(), nullable=True),
    sa.Column('USER_EMAIL', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('USER_NO'),
    sa.UniqueConstraint('UID'),
    sa.UniqueConstraint('USER_EMAIL')
    )
    op.create_table('challenge_master',
    sa.Column('CHALLENGE_MST_NO', sa.Integer(), nullable=False),
    sa.Column('CHALLENGE_MST_NM', sa.String(), nullable=True),
    sa.Column('USERS_UID', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('START_DT', sa.Date(), nullable=True),
    sa.Column('END_DT', sa.Date(), nullable=True),
    sa.Column('HEADER_EMOJI', sa.String(), nullable=True),
    sa.Column('INSERT_DT', sa.DateTime(), nullable=True),
    sa.Column('INSERT_USER_UID', sa.Integer(), nullable=False),
    sa.Column('DELETE_DT', sa.DateTime(), nullable=True),
    sa.Column('DELETE_YN', sa.Boolean(), nullable=True),
    sa.Column('CHALLENGE_STATUS', sa.Enum('PENDING', 'ACTIVE', 'COMPLETE', 'FAILED', name='ChallengeStatus'), nullable=True),
    sa.ForeignKeyConstraint(['INSERT_USER_UID'], ['user.UID'], ),
    sa.PrimaryKeyConstraint('CHALLENGE_MST_NO')
    )
    op.create_table('daily_complete',
    sa.Column('PERSON_DAILY_NO', sa.Integer(), nullable=False),
    sa.Column('CHALLENGE_MST_ID', sa.Integer(), nullable=True),
    sa.Column('INSERT_USER_UID', sa.Integer(), nullable=True),
    sa.Column('AUTH_IMAGE_FILE_NM', sa.String(), nullable=True),
    sa.Column('INSERT_DT', sa.DateTime(), nullable=True),
    sa.Column('COMMENTS', sa.String(), nullable=True),
    sa.Column('PERSON_GOAL_LIST', sa.JSON(), nullable=True),
    sa.Column('REACTION_EMOJI', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_MST_ID'], ['challenge_master.CHALLENGE_MST_NO'], ),
    sa.ForeignKeyConstraint(['INSERT_USER_UID'], ['user.UID'], ),
    sa.PrimaryKeyConstraint('PERSON_DAILY_NO')
    )
    op.create_table('team_goal',
    sa.Column('TEAM_GOAL_NO', sa.Integer(), nullable=False),
    sa.Column('TEAM_GOAL_NM', sa.String(), nullable=True),
    sa.Column('CHALLENGE_MST_ID', sa.Integer(), nullable=True),
    sa.Column('TEAM_LEADER_ID', sa.Integer(), nullable=True),
    sa.Column('COMPLETE_USERS', sa.JSON(), nullable=True),
    sa.Column('START_DT', sa.Date(), nullable=True),
    sa.Column('END_DT', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_MST_ID'], ['challenge_master.CHALLENGE_MST_NO'], ),
    sa.ForeignKeyConstraint(['TEAM_LEADER_ID'], ['user.UID'], ),
    sa.PrimaryKeyConstraint('TEAM_GOAL_NO')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_goal')
    op.drop_table('daily_complete')
    op.drop_table('challenge_master')
    op.drop_table('user')
    # ### end Alembic commands ###
