"""empty message

Revision ID: 7f501f860fa3
Revises: 461d4bc581ee
Create Date: 2023-12-01 00:17:42.917152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f501f860fa3'
down_revision: Union[str, None] = '461d4bc581ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_user',
    sa.Column('ITEM_USER_NO', sa.Integer(), nullable=False),
    sa.Column('COUNT', sa.Integer(), nullable=True),
    sa.Column('ITEM_NO', sa.Integer(), nullable=True),
    sa.Column('CHALLENGE_USER_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_USER_NO'], ['challenge_users.CHALLENGE_USER_NO'], ),
    sa.ForeignKeyConstraint(['ITEM_NO'], ['item.ITEM_NO'], ),
    sa.PrimaryKeyConstraint('ITEM_USER_NO')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_user')
    # ### end Alembic commands ###
