"""empty message

Revision ID: 8508e90bd953
Revises: 72ef825b872f
Create Date: 2023-12-04 20:12:32.127252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8508e90bd953'
down_revision: Union[str, None] = '72ef825b872f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('additional_goal', 'ADDITIONAL_NM',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('avatar_user', 'IS_EQUIP',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('challenge_master', 'CHALLENGE_MST_NM',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('challenge_master', 'START_DT',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('challenge_master', 'END_DT',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('challenge_master', 'HEADER_EMOJI',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('challenge_users', 'IS_OWNER',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('daily_complete_user', 'EMOJI',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('person_daily_goal', 'PERSON_NM',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('team_weekly_goal', 'START_DT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('team_weekly_goal', 'END_DT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user', 'USER_NM',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'USER_NM',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('team_weekly_goal', 'END_DT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('team_weekly_goal', 'START_DT',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('person_daily_goal', 'PERSON_NM',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('daily_complete_user', 'EMOJI',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('challenge_users', 'IS_OWNER',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('challenge_master', 'HEADER_EMOJI',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('challenge_master', 'END_DT',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('challenge_master', 'START_DT',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('challenge_master', 'CHALLENGE_MST_NM',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('avatar_user', 'IS_EQUIP',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('additional_goal', 'ADDITIONAL_NM',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
