"""empty message

Revision ID: 9253ec39d2de
Revises: f72574e15ace
Create Date: 2023-12-01 23:29:42.809104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9253ec39d2de'
down_revision: Union[str, None] = 'f72574e15ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_users', sa.Column('COMMENT', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('challenge_users', 'COMMENT')
    # ### end Alembic commands ###
