"""empty message

Revision ID: 954243be42b6
Revises: 8c37c95aca69
Create Date: 2023-11-28 07:34:43.404413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954243be42b6'
down_revision: Union[str, None] = '8c37c95aca69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_complete_user',
    sa.Column('DAILY_COMPLETE_USER_NO', sa.Integer(), nullable=False),
    sa.Column('EMOJI', sa.String(), nullable=True),
    sa.Column('DAILY_COMPLETE_NO', sa.Integer(), nullable=True),
    sa.Column('CHALLENGE_USER_NO', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_USER_NO'], ['challenge_users.CHALLENGE_USER_NO'], ),
    sa.ForeignKeyConstraint(['DAILY_COMPLETE_NO'], ['person_daily_goal_complete.DAILY_COMPLETE_NO'], ),
    sa.PrimaryKeyConstraint('DAILY_COMPLETE_USER_NO')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_complete_user')
    # ### end Alembic commands ###
