"""empty message

Revision ID: 9ffb685900c8
Revises: 7461f5d9a56f
Create Date: 2023-12-27 08:01:56.474139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ffb685900c8'
down_revision: Union[str, None] = '7461f5d9a56f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_weekly_goal')
    op.alter_column('person_daily_goal_complete', 'INSERT_DT',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person_daily_goal_complete', 'INSERT_DT',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_table('team_weekly_goal',
    sa.Column('TEAM_NO', sa.INTEGER(), server_default=sa.text('nextval(\'"team_weekly_goal_TEAM_NO_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('TEAM_NM', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('IS_DONE', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('START_DT', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('END_DT', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('INSERT_DT', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('MODIFY_DT', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('CHALLENGE_USER_NO', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['CHALLENGE_USER_NO'], ['challenge_users.CHALLENGE_USER_NO'], name='team_weekly_goal_CHALLENGE_USER_NO_fkey'),
    sa.PrimaryKeyConstraint('TEAM_NO', name='team_weekly_goal_pkey')
    )
    # ### end Alembic commands ###
