"""empty message

Revision ID: a693f37246c8
Revises: 3bf215ae2634
Create Date: 2023-12-28 14:41:56.431573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a693f37246c8'
down_revision: Union[str, None] = '3bf215ae2634'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('item_log_RECIPIENT_NO_fkey', 'item_log', type_='foreignkey')
    op.drop_constraint('item_log_SENDER_NO_fkey', 'item_log', type_='foreignkey')
    op.create_foreign_key(None, 'item_log', 'challenge_users', ['SENDER_NO'], ['CHALLENGE_USER_NO'], ondelete='CASCADE')
    op.create_foreign_key(None, 'item_log', 'challenge_users', ['RECIPIENT_NO'], ['CHALLENGE_USER_NO'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_log', type_='foreignkey')
    op.drop_constraint(None, 'item_log', type_='foreignkey')
    op.create_foreign_key('item_log_SENDER_NO_fkey', 'item_log', 'challenge_users', ['SENDER_NO'], ['CHALLENGE_USER_NO'])
    op.create_foreign_key('item_log_RECIPIENT_NO_fkey', 'item_log', 'challenge_users', ['RECIPIENT_NO'], ['CHALLENGE_USER_NO'])
    # ### end Alembic commands ###
