"""empty message

Revision ID: b588c73c1f0a
Revises: f9976760137d
Create Date: 2023-12-04 11:30:48.762034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b588c73c1f0a'
down_revision: Union[str, None] = 'f9976760137d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_log', sa.Column('SENDER_NO', sa.Integer(), nullable=True))
    op.add_column('item_log', sa.Column('RECIPIENT_NO', sa.Integer(), nullable=True))
    op.drop_constraint('item_log_RECIPIENT_UID_fkey', 'item_log', type_='foreignkey')
    op.drop_constraint('item_log_SENDER_UID_fkey', 'item_log', type_='foreignkey')
    op.create_foreign_key(None, 'item_log', 'challenge_users', ['RECIPIENT_NO'], ['CHALLENGE_USER_NO'])
    op.create_foreign_key(None, 'item_log', 'challenge_users', ['SENDER_NO'], ['CHALLENGE_USER_NO'])
    op.drop_column('item_log', 'RECIPIENT_UID')
    op.drop_column('item_log', 'SENDER_UID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_log', sa.Column('SENDER_UID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('item_log', sa.Column('RECIPIENT_UID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item_log', type_='foreignkey')
    op.drop_constraint(None, 'item_log', type_='foreignkey')
    op.create_foreign_key('item_log_SENDER_UID_fkey', 'item_log', 'challenge_users', ['SENDER_UID'], ['CHALLENGE_USER_NO'])
    op.create_foreign_key('item_log_RECIPIENT_UID_fkey', 'item_log', 'challenge_users', ['RECIPIENT_UID'], ['CHALLENGE_USER_NO'])
    op.drop_column('item_log', 'RECIPIENT_NO')
    op.drop_column('item_log', 'SENDER_NO')
    # ### end Alembic commands ###
