"""empty message

Revision ID: c808d2861180
Revises: e2ba6bfb0f27
Create Date: 2023-12-04 03:15:36.564345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c808d2861180'
down_revision: Union[str, None] = 'e2ba6bfb0f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_setting', sa.Column('NOTICE_PUSH_AD_YN', sa.Boolean(), nullable=True))
    op.add_column('user_setting', sa.Column('NOTICE_PUSH_AD_DT', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_setting', 'NOTICE_PUSH_AD_DT')
    op.drop_column('user_setting', 'NOTICE_PUSH_AD_YN')
    # ### end Alembic commands ###
