"""empty message

Revision ID: cb8fd3731eda
Revises: e1d3300e7cf2
Create Date: 2024-01-09 12:17:08.594607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb8fd3731eda'
down_revision: Union[str, None] = 'e1d3300e7cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person_daily_goal', sa.Column('DAILY_COMPLETE_NO', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'person_daily_goal', 'person_daily_goal_complete', ['DAILY_COMPLETE_NO'], ['DAILY_COMPLETE_NO'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person_daily_goal', type_='foreignkey')
    op.drop_column('person_daily_goal', 'DAILY_COMPLETE_NO')
    # ### end Alembic commands ###
