"""empty message

Revision ID: e1d3300e7cf2
Revises: 60032f4fcb14
Create Date: 2024-01-01 01:14:13.784877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1d3300e7cf2'
down_revision: Union[str, None] = '60032f4fcb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_users', sa.Column('IS_VIEW', sa.Boolean(), nullable=True))
    op.drop_column('challenge_users', 'IS_LEADER')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('challenge_users', sa.Column('IS_LEADER', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('challenge_users', 'IS_VIEW')
    # ### end Alembic commands ###
