"""empty message

Revision ID: e736e972ccb8
Revises: c808d2861180
Create Date: 2023-12-04 03:23:57.928560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e736e972ccb8'
down_revision: Union[str, None] = 'c808d2861180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('SENDER_NO', sa.Integer(), nullable=True))
    op.add_column('friend', sa.Column('RECIPIENT_NO', sa.Integer(), nullable=True))
    op.drop_constraint('friend_RECIPIENT_UID_fkey', 'friend', type_='foreignkey')
    op.drop_constraint('friend_SENDER_UID_fkey', 'friend', type_='foreignkey')
    op.create_foreign_key(None, 'friend', 'user', ['SENDER_NO'], ['USER_NO'])
    op.create_foreign_key(None, 'friend', 'user', ['RECIPIENT_NO'], ['USER_NO'])
    op.drop_column('friend', 'SENDER_UID')
    op.drop_column('friend', 'RECIPIENT_UID')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('friend', sa.Column('RECIPIENT_UID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('friend', sa.Column('SENDER_UID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'friend', type_='foreignkey')
    op.drop_constraint(None, 'friend', type_='foreignkey')
    op.create_foreign_key('friend_SENDER_UID_fkey', 'friend', 'user', ['SENDER_UID'], ['USER_NO'])
    op.create_foreign_key('friend_RECIPIENT_UID_fkey', 'friend', 'user', ['RECIPIENT_UID'], ['USER_NO'])
    op.drop_column('friend', 'RECIPIENT_NO')
    op.drop_column('friend', 'SENDER_NO')
    # ### end Alembic commands ###
