"""empty message

Revision ID: f72574e15ace
Revises: e068f321c502
Create Date: 2023-12-01 10:13:20.077303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f72574e15ace'
down_revision: Union[str, None] = 'e068f321c502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avatar',
    sa.Column('AVATAR_NO', sa.Integer(), nullable=False),
    sa.Column('AVATAR_NM', sa.String(), nullable=False),
    sa.Column('AVATAR_TYPE', sa.Enum('CHARACTER', 'PET', name='AvatarType'), nullable=True),
    sa.PrimaryKeyConstraint('AVATAR_NO')
    )
    op.create_table('item',
    sa.Column('ITEM_NO', sa.Integer(), nullable=False),
    sa.Column('ITEM_NM', sa.Enum('BOOM', 'HAMMER', name='ItemType'), nullable=False),
    sa.PrimaryKeyConstraint('ITEM_NO')
    )
    op.add_column('avatar_user', sa.Column('AVATAR_NO', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'avatar_user', 'avatar', ['AVATAR_NO'], ['AVATAR_NO'])
    op.add_column('item_user', sa.Column('ITEM_NO', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item_user', 'item', ['ITEM_NO'], ['ITEM_NO'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_user', type_='foreignkey')
    op.drop_column('item_user', 'ITEM_NO')
    op.drop_constraint(None, 'avatar_user', type_='foreignkey')
    op.drop_column('avatar_user', 'AVATAR_NO')
    op.drop_table('item')
    op.drop_table('avatar')
    # ### end Alembic commands ###
